{
  // only for the compiler, not the IDE
  generate=[
    java='11'
    psi-factory='no'
    visitor='no'
  ]
  generatePsi=false

  // we only need the parser and element types.
  parserClass='org.steeleagle.parser.BotPsiParser'
  elementTypeHolderClass='org.steeleagle.parser.BotPsiElementTypes'
  elementTypeClass='org.steeleagle.parser.BotPsiElementType'
  tokenTypeClass='org.steeleagle.parser.BotPsiTokenType'
}

bro ::= NUMBER addNumber*
addNumber ::= (PLUS | MINUS) NUMBER
